# Generated by rspec-sinatra. (2016-07-02 11:53:58 -0400)

ENV['RACK_ENV'] = 'test'
ENV['WEBHOOK_ENDPOINT'] = '/payload'
ENV['ORG_NAME'] = 'Organization'
ENV['CONTRIBUTOR_TEAM_ID'] = '1234567'
ENV['INVITATION_MESSAGE'] = 'Thanks!'
ENV['GITHUB_TOKEN'] = '12jove8hgowbuv'

require File.join(File.dirname(__FILE__), '..', 'lib/server.rb')
require File.join(File.dirname(__FILE__), '..', 'lib/api.rb')

require 'capybara'
require 'capybara/rspec'
require 'rspec'

Capybara.app = AerynApp
RSpec.configure do |config|
  config.include Capybara::DSL

  config.color = true

  config.expect_with :rspec do |expectations|
    expectations.include_chain_clauses_in_custom_matcher_descriptions = true
  end

  config.order = :random
  Kernel.srand config.seed
end
